
run:
	uv run main.py re-read-dnsr


delete_all_dnsr_nodes:
	uv run delete_all_dnsr_nodes

start_jupyter_server:
	uv run jupyter notebook  --MultiKernelManager.default_kernel_name=apache-age-test vis.ipynb
